Repository thediylabs/thediylabs, pull requests merged in 2019-10, with the labels that each got.

#4 renamed files
  tdl-experience/.gitignore
  tdl-experience/.mvn/wrapper/MavenWrapperDownloader.java
  tdl-experience/.mvn/wrapper/maven-wrapper.jar
  tdl-experience/.mvn/wrapper/maven-wrapper.properties
  tdl-experience/mvnw
  tdl-experience/mvnw.cmd
  tdl-experience/pom.xml
  tdl-experience/src/main/java/com/diy/labs/experience/ExperienceApplication.java
  tdl-experience/src/main/java/com/diy/labs/experience/web/controller/ProductsController.java
  tdl-experience/src/main/java/com/diy/labs/experience/web/controller/SearchController.java
  tdl-experience/src/main/resources/application.properties
  tdl-experience/src/test/java/com/diy/labs/experience/ExperienceApplicationTests.java
  tdl-model/.DS_Store
  tdl-model/.gitignore
  tdl-model/.mvn/wrapper/MavenWrapperDownloader.java
  tdl-model/.mvn/wrapper/maven-wrapper.jar
  tdl-model/.mvn/wrapper/maven-wrapper.properties
  tdl-model/mvnw
  tdl-model/mvnw.cmd
  tdl-model/pom.xml
  tdl-model/src/.DS_Store
  tdl-model/src/main/.DS_Store
  tdl-model/src/main/java/com/diy/labs/model/common/DIYLABLombokAnnotator.java
  tdl-model/src/main/java/com/diy/labs/model/common/DIYLABLombokPropertyRule.java
  tdl-model/src/main/java/com/diy/labs/model/common/DIYLABLombokRuleFactory.java
  tdl-model/src/main/java/com/diy/labs/model/common/Truncate.java
  tdl-model/src/main/java/com/diy/labs/model/common/TruncateRule.java
  tdl-model/src/main/resources/.DS_Store
  tdl-model/src/main/resources/application.properties
  tdl-model/src/main/resources/schemas/.DS_Store
Labels: documentation

#5 https://trello.com/c/pJ0HIPYL/7-lint-test-jest-ui
  tdl-app/.eslintignore
  tdl-app/.eslintrc.json
  tdl-app/package-lock.json
  tdl-app/package.json
  tdl-app/src/serviceWorker.js
Labels: enhancement

#11 Landing, Products, Detailed Products Page UI
  tdl-app/package-lock.json
  tdl-app/package.json
  tdl-app/src/App.css
  tdl-app/src/App.js
  tdl-app/src/App.test.js
  tdl-app/src/components/ApplicationBar/ApplicationBar.js
  tdl-app/src/components/ApplicationBar/ApplicationBar.spec.js
  tdl-app/src/components/ApplicationBar/__snapshots__/ApplicationBar.spec.js.snap
  tdl-app/src/components/ApplicationBar/index.js
  tdl-app/src/components/CategoryTile/CategoryTile.js
  tdl-app/src/components/CategoryTile/CategoryTile.spec.js
  tdl-app/src/components/CategoryTile/__snapshots__/CategoryTile.spec.js.snap
  tdl-app/src/components/CategoryTile/index.js
  tdl-app/src/components/ProductTile/ProductTile.js
  tdl-app/src/components/ProductTile/ProductTile.spec.js
  tdl-app/src/components/ProductTile/__snapshots__/ProductTile.spec.js.snap
  tdl-app/src/components/ProductTile/index.js
  tdl-app/src/index.js
  tdl-app/src/logo.svg
  tdl-app/src/pages/App.js
  tdl-app/src/pages/App.test.js
  tdl-app/src/pages/DetailedProduct/DetailedProduct.js
  tdl-app/src/pages/DetailedProduct/DetailedProduct.spec.js
  tdl-app/src/pages/DetailedProduct/__snapshots__/DetailedProduct.spec.js.snap
  tdl-app/src/pages/DetailedProduct/index.js
  tdl-app/src/pages/Landing/Landing.js
  tdl-app/src/pages/Landing/Landing.spec.js
  tdl-app/src/pages/Landing/__snapshots__/Landing.spec.js.snap
  tdl-app/src/pages/Landing/index.js
  tdl-app/src/pages/Products/Products.js
  tdl-app/src/pages/Products/Products.spec.js
  tdl-app/src/pages/Products/__snapshots__/Products.spec.js.snap
  tdl-app/src/pages/Products/index.js
  tdl-app/src/pages/__snapshots__/App.test.js.snap
Labels: Ready for Review
